project:
  type: website
  output-dir: docs

website:
  title: "TEAM_What-is-the-dinner-menu_new"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: practice presentaion.qmd
        text: presentaion 0
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

